# Generated by Django 4.2 on 2023-10-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_taxable',
            field=models.BooleanField(default=True),
        ),
    ]
