# Generated by Django 4.2 on 2023-10-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('invoices', '0003_invoice_is_taxable'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, related_name='invoice_items', to='inventory.inventory'),
        ),
    ]
