# Generated by Django 4.2 on 2023-10-10 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_discount_invoice_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='lens',
        ),
    ]
