# Generated by Django 4.2 on 2023-11-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_invoice_advance_payment_mode_invoicepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepayment',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicepayment',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
