# Generated by Django 4.2 on 2023-11-22 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventorycsv_status'),
        ('invoices', '0009_invoice_tax_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='items',
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice')),
            ],
            options={
                'unique_together': {('invoice', 'inventory_item')},
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='inventory_items',
            field=models.ManyToManyField(blank=True, null=True, related_name='inventory_items', through='invoices.InvoiceItem', to='inventory.inventory'),
        ),
    ]
