# Generated by Django 4.2 on 2023-11-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventorycsv_status'),
        ('invoices', '0011_remove_invoice_inventory_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, related_name='inventory_items', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='cost_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost Value Snapshot'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='sale_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sale Value Snapshot'),
        ),
    ]
