# Generated by Django 4.2 on 2023-11-28 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_invoice_items_invoiceitem_cost_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepayment',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_payment', to='invoices.invoice'),
        ),
    ]
