# Generated by Django 4.2 on 2023-12-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_payment_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='total_customers',
            field=models.PositiveIntegerField(default=0, verbose_name='total_customers'),
        ),
        migrations.AddField(
            model_name='organization',
            name='total_inventory',
            field=models.PositiveIntegerField(default=0, verbose_name='total_inventory'),
        ),
        migrations.AddField(
            model_name='organization',
            name='total_invoices',
            field=models.PositiveIntegerField(default=0, verbose_name='total_invoices'),
        ),
        migrations.AddField(
            model_name='organization',
            name='total_prescriptions',
            field=models.PositiveIntegerField(default=0, verbose_name='total_prescriptions'),
        ),
    ]
