# Generated by Django 4.2.4 on 2024-01-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_organization_customer_statistics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trial_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
