# Generated by Django 4.2.4 on 2024-01-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_subscription_trial_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Expired', 'Expired'), ('Pending', 'Pending'), ('Error', 'Error'), ('Stopped', 'Stopped'), ('Trial', 'Trial')], default='Trial', max_length=10),
        ),
    ]
