# Generated by Django 4.2 on 2024-06-05 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0010_subscription_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WholeSaleVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_person_phone', models.CharField(max_length=100)),
                ('contact_person_email', models.EmailField(max_length=254)),
                ('contact_person_designation', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wholesale_vendor_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_vendor', to='organizations.organization')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wholesale_vendor_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WholeSaleInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('item_type', models.CharField(max_length=100)),
                ('item_property', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('part_model_no', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('basic_unit_of_measure', models.CharField(max_length=100)),
                ('std_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price_2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price_3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('re_order_qty', models.IntegerField()),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_discount_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor_ref_no', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wholesale_inventory_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_inventory', to='organizations.organization')),
                ('preferred_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_inventory', to='wholesale.wholesalevendor')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wholesale_inventory_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
