# Generated by Django 4.2 on 2024-06-05 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0003_wholesaleorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('selected_selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.wholesaleinventory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wholesale.wholesaleorder')),
            ],
        ),
    ]
