# Generated by Django 4.2 on 2024-06-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0007_alter_wholesaleclient_last_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaleclient',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wholesaleorder',
            name='is_taxable',
            field=models.BooleanField(default=True),
        ),
    ]
