# Generated by Django 4.2 on 2024-06-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0008_wholesaleclient_tax_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitems',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
