# Generated by Django 4.2 on 2023-09-27 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Stock Keeping Unit')),
                ('store_sku', models.CharField(blank=True, max_length=255, null=True, verbose_name='Store SKU')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('qty', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('sale_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sale Value')),
                ('cost_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost Value')),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='organizations.organization')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
