# Generated by Django 4.2 on 2023-10-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='item_type',
            field=models.CharField(choices=[('Frames', 'Frames'), ('Lens', 'Lens'), ('Others', 'Others')], default='Frames', max_length=10),
        ),
    ]
