# Generated by Django 4.2 on 2023-11-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='item_type',
            field=models.CharField(choices=[('Lens', 'Lens'), ('Frames', 'Frames'), ('Other', 'Other')], default='Lens', max_length=15),
        ),
    ]
