# Generated by Django 4.2 on 2023-11-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item_type',
            field=models.CharField(choices=[('Frames', 'Frames'), ('Lens', 'Lens'), ('Others', 'Others')], default='Frames', max_length=10),
        ),
    ]
