# Generated by Django 4.2 on 2023-11-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('Stocked', 'Stocked'), ('Out of Stock', 'Out of Stock'), ('Others', 'Others')], default='Stocked', max_length=20),
        ),
    ]
