# Generated by Django 4.2 on 2023-11-17 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0005_payment_subscription'),
        ('inventory', '0004_inventory_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Processing', 'Processing'), ('Error', 'Error')], default='Created', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=1024, null=True)),
                ('csv_file', models.ImageField(blank=True, null=True, upload_to='organization_csv/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories_csv_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories_csv', to='organizations.organization')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories_csv_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
