# Generated by Django 4.2 on 2023-11-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventorycsv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycsv',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='organization_csv/'),
        ),
    ]
