# Generated by Django 4.2 on 2023-11-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventorycsv_csv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycsv',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Error', 'Error')], default='Created', max_length=20),
        ),
    ]
